title: Xiaorui Liu
url: "xiaoruiyliu.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/"
 - name: "teaching"
   link: "projects"
 - name: "contact"
   link: "contact"
